CREATE TABLE "expenditures" (
  "exp_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year" smallint,
  "month" smallint,
  "day" smallint,
  "qt" smallint,
  "department" varchar(50),
  "exp_type" integer,
  "record_amount" integer,
  "actual_amount" integer,
  "confirmed_by" varchar(50),
  "claimed_by" varchar(50),
  "cheque_no" integer,
  "isPaid" bool,
  "notes" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "paid_at" timestamp
);

CREATE TABLE "invoices" (
  "inv_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" varchar(10),
  "item" varchar(100),
  "details" varchar(255),
  "amount" integer,
  "created_at" timestamp DEFAULT (now()),
  "exp_id" integer
);

CREATE TABLE "categories" (
  "ctg_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isParent" bool,
  "depth" char(3),
  "range" char(3),
  "name" varchar(20),
  "detail" varchar(255),
  "order" smallint
);

CREATE TABLE "receipts" (
  "rcp_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exp_id" integer,
  "file_path" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "income" (
  "inc_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inc_type" integer,
  "amount" integer,
  "member" integer,
  "year" smallint,
  "month" smallint,
  "day" smallint,
  "qt" smallint,
  "notes" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "members" (
  "mbr_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_full" varchar(20),
  "details" varchar(255),
  "address" varchar(50),
  "city" varchar(20),
  "province" varchar(20),
  "postal" varchar(7),
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "expenditures" ("year");

CREATE INDEX ON "expenditures" ("month");

CREATE INDEX ON "expenditures" ("qt");

CREATE INDEX ON "income" ("year");

CREATE INDEX ON "income" ("month");

CREATE INDEX ON "income" ("qt");

ALTER TABLE "invoices" ADD FOREIGN KEY ("exp_id") REFERENCES "expenditures" ("exp_id");

ALTER TABLE "expenditures" ADD FOREIGN KEY ("exp_type") REFERENCES "categories" ("ctg_id");

ALTER TABLE "income" ADD FOREIGN KEY ("inc_type") REFERENCES "categories" ("ctg_id");

ALTER TABLE "receipts" ADD FOREIGN KEY ("exp_id") REFERENCES "expenditures" ("exp_id");

ALTER TABLE "income" ADD FOREIGN KEY ("member") REFERENCES "members" ("mbr_id");

CREATE VIEW income_list AS
SELECT
    income.inc_id,
    income.amount,
    income.notes,
    income.year,
    income.month,
    income.day,
    categories."name" AS "type",
    members."name_full" AS "member",
    qt
FROM income
JOIN categories ON income."inc_type" = categories."ctg_id"
JOIN members ON members."mbr_id" = income."member"
ORDER BY year, month, day desc;

ALTER VIEW income_list
RENAME member TO name;

INSERT INTO "public"."Category" ("ctg_id", "isParent", "depth", "range", "name", "detail", "order") VALUES
(1, 't', '100', 'inc', 'Ministry', '주일헌금', 1),
(2, 't', '100', 'inc', 'Thanks', '감사헌금', 2),
(3, 't', '100', 'inc', 'Tithe', '십일조', 3),
(4, 't', '100', 'inc', 'Mission', '선교헌금', 4),
(5, 't', '100', 'inc', 'Share', '나눔헌금', 5),
(6, 't', '100', 'inc', 'Bank', '은행수입 (이자 등)', 6),
(7, 't', '100', 'inc', 'ETC', '기타', 7);


INSERT INTO "public"."Category" ("ctg_id", "isParent", "depth", "range", "name", "detail", "order") VALUES
(8, 't', '100', 'imd', 'Cash', '현금', 1),
(9, 't', '100', 'imd', 'Cheque', '수표', 2),
(10, 't', '100', 'imd', 'E-Transfer', '이트랜스퍼', 3),
(11, 't', '100', 'imd', 'Credit', '신용카드', 4),
(12, 't', '100', 'imd', 'Foreign', '외환', 5)